// Datos de vehículos en subasta
export const subastaData = [

  {
    id: 1,
    marca: "Brilliance",
    modelo: "H220",
    año: 2015,
    precio: 2100,
    imagen: "/Autos/brilliance/1.jpeg",
    imagenes: [
      "/Autos/brilliance/1.jpeg",
      "/Autos/brilliance/2.jpeg",
      "/Autos/brilliance/3.jpeg",
      "/Autos/brilliance/4.jpeg",
      "/Autos/brilliance/5.jpeg",
      "/Autos/brilliance/6.jpeg",
      "/Autos/brilliance/7.jpeg",
      "/Autos/brilliance/8.jpeg",
      "/Autos/brilliance/9.jpeg",
      "/Autos/brilliance/10.jpeg",
    ],  
    kilometraje: "170,000 km",
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina/GLP",
    color: "Anaranjado",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2025-12-11T16:00:00",
    anexoUrl: "/anexo/TyC.pdf",
    boletaInformativaUrl: null,
    descripcion:  [
      "<strong>Nota importante:</strong> El comprador acepta que el vehículo podría tener papeletas, multas o cargas desconocidas por el vendedor al momento de la venta, y asume toda responsabilidad por cualquier afectación que aparezca después de la transferencia.",
      "",
      "La venta de los vehículos se realiza en la modalidad de \"donde está y como está\".",
      "Los datos y fotografías son referenciales.",
      "Es responsabilidad del comprador verificar que el número de serie y número de motor correspondan a la unidad.",
      "El trámite de cambio de placas y entrega del SOAT vigente no está a cargo de la compañía.",
      "Todos los gastos relacionados a la logística, transporte o cualquier otro, serán pagados por el comprador y deben ser cancelados antes de la entrega del vehículo.",
      "",
      "El precio no incluye IGV. Debe agregar 5% de comisión al precio mostrado.",
      "Para poder participar en la subasta, el comprador debe haber depositado su garantia de s/300.00 en la cuenta bancaria indicada por la empresa."
    ].join("\n"),
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Tela",
      "Cámara de reversa",
      "Aros de aleacion", 
      "GLP",
      "Transmision mecanica",
      "Frenos ABS"
    ]
  },
  {
    id: 2,
    marca: "BYD",
    modelo: "f3",
    año: 2017,
    precio: 2100,
    imagen: "/Autos/bydF3/4.jpeg",
    imagenes: [
      "/Autos/bydF3/1.jpeg",
      "/Autos/bydF3/2.jpeg",
      "/Autos/bydF3/3.jpeg",
      "/Autos/bydF3/4.jpeg",
      "/Autos/bydF3/5.jpeg",
      "/Autos/bydF3/6.jpeg",
      "/Autos/bydF3/7.jpeg",
      "/Autos/bydF3/8.jpeg",
      "/Autos/bydF3/9.jpeg",
      "/Autos/bydF3/10.jpeg",
    ],  
    kilometraje: "230,000 km",
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina/GNV",
    color: "Negro",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2025-12-11T16:30:00",
    anexoUrl: "/anexo/TyC.pdf",
    boletaInformativaUrl: null,
    descripcion:  [
      "<strong>Nota importante:</strong> El comprador acepta que el vehículo podría tener papeletas, multas o cargas desconocidas por el vendedor al momento de la venta, y asume toda responsabilidad por cualquier afectación que aparezca después de la transferencia.",
      "",
      "La venta de los vehículos se realiza en la modalidad de \"donde está y como está\".",
      "Los datos y fotografías son referenciales.",
      "Es responsabilidad del comprador verificar que el número de serie y número de motor correspondan a la unidad.",
      "El trámite de cambio de placas y entrega del SOAT vigente no está a cargo de la compañía.",
      "Todos los gastos relacionados a la logística, transporte o cualquier otro, serán pagados por el comprador y deben ser cancelados antes de la entrega del vehículo.",
      "",
      "El precio no incluye IGV. Debe agregar 5% de comisión al precio mostrado.",
      "Para poder participar en la subasta, el comprador debe haber depositado su garantia de s/300.00 en la cuenta bancaria indicada por la empresa."
    ].join("\n"),
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Cuero",
      "Cámara de reversa",
      "Aros de aleacion", 
      "GNV",
      "Transmision mecanica",
      "Frenos ABS",
      "pantalla touch"
    ]
  },

  {
    id: 3,
    marca: "Kia",
    modelo: "Rio",
    año: 2017,  
    precio: 4500,
    imagen: "/Autos/kiario/1.jpg",
    imagenes: [
      "/Autos/kiario/1.jpg",
      "/Autos/kiario/2.jpg",
      "/Autos/kiario/3.jpg",
      "/Autos/kiario/4.jpg",
      "/Autos/kiario/5.jpg",
      "/Autos/kiario/6.jpg",
      "/Autos/kiario/7.jpg",
      "/Autos/kiario/8.jpg",
      "/Autos/kiario/9.jpg",
    ],  
    kilometraje: "100,000 km",
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina",
    color: "Negro",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2026-01-23T17:00:00",
    anexoUrl: "/anexo/TyC.pdf",
    boletaInformativaUrl: "/Autos/kiario/ATQ-598.pdf",
    descripcion:  [
      "<strong>Nota importante:</strong> El comprador acepta que el vehículo podría tener papeletas, multas o cargas desconocidas por el vendedor al momento de la venta, y asume toda responsabilidad por cualquier afectación que aparezca después de la transferencia.",
      "",
      "La venta de los vehículos se realiza en la modalidad de \"donde está y como está\".",
      "Los datos y fotografías son referenciales.",
      "Es responsabilidad del comprador verificar que el número de serie y número de motor correspondan a la unidad.",
      "El trámite de cambio de placas y entrega del SOAT vigente no está a cargo de la compañía.",
      "Todos los gastos relacionados a la logística, transporte o cualquier otro, serán pagados por el comprador y deben ser cancelados antes de la entrega del vehículo.",
      "",
      "El precio no incluye IGV. Debe agregar 5% de comisión al precio mostrado.",
      "Para poder participar en la subasta, el comprador debe haber depositado su garantia de s/300.00 en la cuenta bancaria indicada por la empresa."
    ].join("\n"),
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Cuero",
      "Cámara de reversa",
      "Aros de aleacion", 
      "GNV",
      "Transmision mecanica",
      "Frenos ABS",
      "pantalla touch"
    ]
  },
  {
    id: 4,
    marca: "RAM",
    modelo: "v700",
    año: 2022,  
    precio: 5300,
    imagen: "/Autos/ramv700/1.jpeg",
    imagenes: [
      "/Autos/ramv700/1.jpeg",
      "/Autos/ramv700/2.jpeg",
      "/Autos/ramv700/3.jpeg",
      "/Autos/ramv700/4.jpeg",
      "/Autos/ramv700/5.jpeg",
      "/Autos/ramv700/6.jpeg",
      "/Autos/ramv700/7.jpeg",
      "/Autos/ramv700/8.jpeg",
    ],  
    kilometraje: "61,000 km",
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina",
    color: "Blanco",
    puertas: 2,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2026-01-23T18:15:00",
    anexoUrl: "/anexo/TyC.pdf",
    boletaInformativaUrl: null,
    descripcion:  [
      "<strong>Nota importante:</strong> El comprador acepta que el vehículo podría tener papeletas, multas o cargas desconocidas por el vendedor al momento de la venta, y asume toda responsabilidad por cualquier afectación que aparezca después de la transferencia.",
      "",
      "La venta de los vehículos se realiza en la modalidad de \"donde está y como está\".",
      "Los datos y fotografías son referenciales.",
      "Es responsabilidad del comprador verificar que el número de serie y número de motor correspondan a la unidad.",
      "El trámite de cambio de placas y entrega del SOAT vigente no está a cargo de la compañía.",
      "Todos los gastos relacionados a la logística, transporte o cualquier otro, serán pagados por el comprador y deben ser cancelados antes de la entrega del vehículo.",
      "",
      "El precio no incluye IGV. Debe agregar 5% de comisión al precio mostrado.",
      "Para poder participar en la subasta, el comprador debe haber depositado su garantia de s/300.00 en la cuenta bancaria indicada por la empresa."
    ].join("\n"),
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Cuero",
      "No Cámara de reversa",
      "Aros de aleacion", 
      "Transmision mecanica",
      "Frenos ABS",
    ]
  },
  {
    id: 5,
    marca: "Toyota",
    modelo: "Agya",
    año: 2021,
    precio: 6490,
    imagen: "/Autos/agya/7.jpeg",
    imagenes: [
      "/Autos/agya/7.jpeg",
      "/Autos/agya/1.jpeg",
      "/Autos/agya/2.jpeg",
      "/Autos/agya/3.jpeg",
      "/Autos/agya/4.jpeg",
      "/Autos/agya/5.jpeg",
      "/Autos/agya/6.jpeg",
    ],  
    kilometraje: "000,000 km",  
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina",
    color: "Plateado",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2026-02-06T17:00:00",
    anexoUrl: "/anexo/TyC.pdf",
    boletaInformativaUrl: null,
    descripcion:  [
      "<strong>PLACA: V0S118</strong>",
      "",
      "<strong>Nota importante:</strong> El comprador acepta que el vehículo podría tener papeletas, multas o cargas desconocidas por el vendedor al momento de la venta, y asume toda responsabilidad por cualquier afectación que aparezca después de la transferencia.",
      "",
      "<strong>UBICACION: El vehiculo se encuentra en Lima.</strong>",
      "La venta de los vehículos se realiza en la modalidad de \"donde está y como está\".",
      "Los datos y fotografías son referenciales.",
      "Es responsabilidad del comprador verificar que el número de serie y número de motor correspondan a la unidad.",
      "El trámite de cambio de placas y entrega del SOAT vigente no está a cargo de la compañía.",
      "Todos los gastos relacionados a la logística, transporte o cualquier otro, serán pagados por el comprador y deben ser cancelados antes de la entrega del vehículo.",
      "",
      "El precio no incluye IGV. Debe agregar 5% de comisión al precio mostrado.",
      "Para poder participar en la subasta, el comprador debe haber depositado su garantia de s/300.00 en la cuenta bancaria indicada por la empresa."
    ].join("\n"),
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Tela",
      "Cámara de reversa",
      "Aros de aleacion", 
      "Gasolina",
      "Transmision mecanica",
      "Frenos ABS"
    ]
  },
  {
    id: 6,
    marca: "Chevrolet",
    modelo: "Sail",
    año: 2016,
    precio: 2100,
    imagen: "/Autos/Sail01/1.jpeg",
    imagenes: [
      "/Autos/Sail01/1.jpeg",
      "/Autos/Sail01/2.jpeg",
      "/Autos/Sail01/3.jpeg",
      "/Autos/Sail01/4.jpeg",
      "/Autos/Sail01/5.jpeg",
      "/Autos/Sail01/6.jpeg",
    ],  
    kilometraje: "125,000 km",  
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina",
    color: "Negro",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2026-02-06T17:30:00",
    anexoUrl: "/anexo/TyC.pdf",
    boletaInformativaUrl: "/Autos/Sail01/AYG-065.pdf",
    descripcion:  [
      "<strong>PLACA: AYG065</strong>",
      "<strong>Nota importante:</strong> El comprador acepta que el vehículo podría tener papeletas, multas o cargas desconocidas por el vendedor al momento de la venta, y asume toda responsabilidad por cualquier afectación que aparezca después de la transferencia.",
      "<strong style='color: red;'>DEUDA DEIMPUESTO VEHICULAR EN LIMA: S/4412.00</strong>",
      "<strong>UBICACION: El vehiculo se encuentra en ILAVE, Puno.</strong>",
      "",
      "La venta de los vehículos se realiza en la modalidad de \"donde está y como está\".",
      "Los datos y fotografías son referenciales.",
      "Es responsabilidad del comprador verificar que el número de serie y número de motor correspondan a la unidad.",
      "El trámite de cambio de placas y entrega del SOAT vigente no está a cargo de la compañía, SI CORRESPONDIERA.",
      "Todos los gastos relacionados a la logística, transporte o cualquier otro, serán pagados por el comprador y deben ser cancelados antes de la entrega del vehículo.",
      "",
      "El precio no incluye IGV. Debe agregar 5% de comisión al precio mostrado.",
      "Para poder participar en la subasta, el comprador debe haber depositado su garantia de s/300.00 en la cuenta bancaria indicada por la empresa."
    ].join("\n"),
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Tela",
      "Pantalla Digital",
      "Aros de Serie", 
      "Gasolina",
      "Transmision mecanica",
      "Frenos ABS"
    ]
  },
  {
    id: 7,
    marca: "Hero",
    modelo: "Hunk 125R",
    año: 2026,
    precio: 1500,
    imagen: "/Autos/Hunk/1.jpeg",
    imagenes: [
      "/Autos/Hunk/1.jpeg",
      "/Autos/Hunk/2.jpeg",
      "/Autos/Hunk/3.jpeg",
    ],  
    kilometraje: "16 km",  
    estado: "Excelente",
    transmision: "Mecanica",
    combustible: "Gasolina",
    color: "Negro",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2026-02-06T18:00:00",
    anexoUrl: "/anexo/TyC.pdf",
    boletaInformativaUrl: null,
    descripcion:  [
      "<strong>PLACA: 1534FD</strong>",
      "<strong>Nota importante:</strong> El comprador acepta que el vehículo podría tener papeletas, multas o cargas desconocidas por el vendedor al momento de la venta, y asume toda responsabilidad por cualquier afectación que aparezca después de la transferencia.",
      "<strong>UBICACION: El vehiculo se encuentra en Lima.</strong>",
      "",
      "La venta de los vehículos se realiza en la modalidad de \"donde está y como está\".",
      "Los datos y fotografías son referenciales.",
      "Es responsabilidad del comprador verificar que el número de serie y número de motor correspondan a la unidad.",
      "El trámite de cambio de placas y entrega del SOAT vigente no está a cargo de la compañía, SI CORRESPONDIERA.",
      "Todos los gastos relacionados a la logística, transporte o cualquier otro, serán pagados por el comprador y deben ser cancelados antes de la entrega del vehículo.",
      "",
      "El precio no incluye IGV. Debe agregar 5% de comisión al precio mostrado.",
      "Para poder participar en la subasta, el comprador debe haber depositado su garantia de s/300.00 en la cuenta bancaria indicada por la empresa."
    ].join("\n"),
    caracteristicas: [
      "Pantalla Digital",
      "Aros de Serie", 
      "Llaves: Si", 
      "Gasolina", 
      "Transmision mecanica", 
      "SOAT: No", 
    ]
  },
  {
    id: 8,
    marca: "Chevrolet",
    modelo: "Sail",
    año: 2014,
    precio: 900,
    imagen: "/Autos/sail2/1.jpeg",
    imagenes: [
      "/Autos/sail2/1.jpeg",
    ],  
    kilometraje: "125,000 km",  
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina",
    color: "Negro",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2026-02-06T18:30:00",
    anexoUrl: "/anexo/TyC.pdf",
    boletaInformativaUrl: "/Autos/sail02/ADM-571.pdf",
    descripcion:  [
      "<strong>PLACA: ADM571</strong>",
      "<strong>Nota importante:</strong> El comprador acepta que el vehículo podría tener papeletas, multas o cargas desconocidas por el vendedor al momento de la venta, y asume toda responsabilidad por cualquier afectación que aparezca después de la transferencia.",
      "<strong>UBICACION: El vehiculo se encuentra en Lima.</strong>",
      "",
      "La venta de los vehículos se realiza en la modalidad de \"donde está y como está\".",
      "Los datos y fotografías son referenciales.",
      "Es responsabilidad del comprador verificar que el número de serie y número de motor correspondan a la unidad.",
      "El trámite de cambio de placas y entrega del SOAT vigente no está a cargo de la compañía, SI CORRESPONDIERA.",
      "Todos los gastos relacionados a la logística, transporte o cualquier otro, serán pagados por el comprador y deben ser cancelados antes de la entrega del vehículo.",
      "",
      "El precio no incluye IGV. Debe agregar 5% de comisión al precio mostrado.",
      "Para poder participar en la subasta, el comprador debe haber depositado su garantia de s/300.00 en la cuenta bancaria indicada por la empresa."
    ].join("\n"),
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Tela",
      "Pantalla Digital",
      "Aros de Serie", 
      "Gasolina",
      "Transmision mecanica",
      "Frenos ABS"
    ]
  },
  {
    id: 9,
    marca: "Apple",
    modelo: "Macbook Pro",
    año: 2018,
    precio: 119,
    imagen: "/Autos/macbook/1.png",
    imagenes: [
      "/Autos/macbook/1.png",
      "/Autos/macbook/2.png",
      "/Autos/macbook/3.png",
      "/Autos/macbook/4.png",
    ],  
    kilometraje: "000,000 km",
    estado: "Bueno",
    transmision: "-",
    combustible: "-",
    color: "Plateado",
    puertas: 0,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2026-02-12T18:30:00",
    anexoUrl: "/anexo/TyC.pdf",
    descripcion:  [
      "Macbook pro 2019. Operativo con pocos detalles esteticos",
    ].join("\n"),
    caracteristicas: [
    ]
  },
  {
    id: 10,
    marca: "Apple",
    modelo: "Iphone 14 pro 128GB ",
    año: 2022,
    precio: 119,
    imagen: "/Autos/iphone/1.png",
    imagenes: [
      "/Autos/iphone/1.png",
      "/Autos/iphone/2.png",
      "/Autos/iphone/3.png",
    ],  
    kilometraje: "000,000 km",
    estado: "Bueno",
    transmision: "-",
    combustible: "-",
    color: "Plateado",
    puertas: 0,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2026-02-12T18:30:00",
    anexoUrl: "/anexo/TyC.pdf",
    descripcion:  [
      "Iphone 14 pro 128GB. Operativo sin detalles esteticos",
    ].join("\n"),
    caracteristicas: [
    ]
  },
  
];
