// Datos de vehículos en subasta
export const subastaData = [

  {
    id: 1,
    marca: "Chevrolet",
    modelo: "Colorado",
    año: 2022,
    precio: 13000,
    imagen: "/subasta1/1.jpeg",
    imagenes: [
      "/subasta1/1.jpeg",
      "/subasta1/2.jpeg",
    ],  
    kilometraje: "35,000 km",
    estado: "Excelente",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "Blanco",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2025-12-11T15:00:00",
    descripcion: "Vehículo en excelentes condiciones, mantenimiento al día, un solo dueño. Motor V6, aire acondicionado, sistema de sonido premium, asientos de cuero, cámara de reversa y mucho más.",
    caracteristicas: [
      "Aire acondicionado",
      "Sistema de sonido premium",
      "Asientos de cuero",
      "Cámara de reversa",
      "Bluetooth",
      "Control crucero",
      "Llantas nuevas",
      "Frenos ABS"
    ]
  },
  {
    id: 2,
    marca: "Kia",
    modelo: "Sorento",
    año: 2023,
    precio: 25000,
    imagen: "/subasta2/3.jpeg",
    imagenes: [
      "/subasta2/1.jpeg",
      "/subasta2/2.jpeg",
      "/subasta2/3.jpeg",
      "/subasta2/4.jpeg",
      "/subasta2/5.jpeg",
      "/subasta2/6.jpeg",
      "/subasta2/7.jpeg",
      "/subasta2/8.jpeg",
      "/subasta2/9.jpeg",
      "/subasta2/10.jpeg",
      "/subasta2/11.jpeg",
    ],  
    kilometraje: "67,500 km",
    estado: "Excelente",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "Blanco",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2025-12-11T15:15:00",
    descripcion: "Vehiculo con daños en carroceria, ademas presenta papeletas en Lima y callao.",
    caracteristicas: [
      "Aire acondicionado",
      "Sistema de sonido premium",
      "Asientos de cuero",
      "Cámara de reversa",
      "Bluetooth",
      "Control crucero",
      "Llantas nuevas",
      "SunRoof",
      "Frenos ABS"
    ]
  },
  {
    id: 3,
    marca: "Brilliance",
    modelo: "H220",
    año: 2015,
    precio: 2400,
    imagen: "/brilliance/1.jpeg",
    imagenes: [
      "/brilliance/1.jpeg",
      "/brilliance/2.jpeg",
      "/brilliance/3.jpeg",
      "/brilliance/4.jpeg",
      "/brilliance/5.jpeg",
      "/brilliance/6.jpeg",
      "/brilliance/7.jpeg",
      "/brilliance/8.jpeg",
      "/brilliance/9.jpeg",
      "/brilliance/10.jpeg",
    ],  
    kilometraje: "170,000 km",
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina/GLP",
    color: "Anaranjado",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2025-12-11T15:30:00",
    descripcion: "Vehiculo con daños en carroceria, ademas presenta papeletas en callao.",
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Tela",
      "Cámara de reversa",
      "Aros de aleacion", 
      "GLP",
      "Transmision mecanica",
      "Frenos ABS"
    ]
  },
  {
    id: 4,
    marca: "BYD",
    modelo: "f3",
    año: 2017,
    precio: 2700,
    imagen: "/bydF3/4.jpeg",
    imagenes: [
      "/bydF3/1.jpeg",
      "/bydF3/2.jpeg",
      "/bydF3/3.jpeg",
      "/bydF3/4.jpeg",
      "/bydF3/5.jpeg",
      "/bydF3/6.jpeg",
      "/bydF3/7.jpeg",
      "/bydF3/8.jpeg",
      "/bydF3/9.jpeg",
      "/bydF3/10.jpeg",
    ],  
    kilometraje: "230,000 km",
    estado: "Bueno",
    transmision: "Mecanica",
    combustible: "Gasolina/GNV",
    color: "Negro",
    puertas: 4,
    // Fecha de finalización de la subasta (formato ISO 8601)
    fecha_fin: "2025-12-11T15:45:00",
    descripcion: "Vehiculo con daños en carroceria y pintura.",
    caracteristicas: [
      "Sistema de sonido premium",
      "Asientos de Cuero",
      "Cámara de reversa",
      "Aros de aleacion", 
      "GNV",
      "Transmision mecanica",
      "Frenos ABS",
      "pantalla touch"
    ]
  },


];