import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/navigation/Footer";
import Navbar from "./components/navigation/Navbar";
import VirtualAgent from "./components/VirtualAgent";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Caltimer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light" style={{ colorScheme: 'light' }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <VirtualAgent />
        <Footer />
      </body>
    </html>
  );
}
